# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU


 production:
   qiniu_access_key: 99WC00zT4M8fYqm57M26EQJpwlftFPdlLiBs7N6M  # 你的 qiniu AccessKey

   qiniu_secret_key: P0QRMjbbSpF4Eo_x4T8hOsnT6wne9jYmkcF7aF32  # 你的 qiniu SecretKey

   qiniu_bucket: jdstore-demo2  # 你的 qiniu bucket

   qiniu_bucket_domain: oqvf5d9pq.bkt.clouddn.com  # 你的 qiniu bucket domain

  #  AWS_ACCESS_KEY_ID: "xxxx"
  #  AWS_SECRET_ACCESS_KEY: "xxxx"
  #  AWS_REGION: "xxxx"
  #  AWS_BUCKET_NAME: "xxxx"
   SEND_CLOUD_USER_NAME: "solarmax_test_d8L5Nl"  # 你的 API_USER

   SEND_CLOUD_USER_KEY: "55Zn2AVgt9VGXSGq"  # 你的 API_KEY


 development:
   qiniu_access_key: 99WC00zT4M8fYqm57M26EQJpwlftFPdlLiBs7N6M  # 你的 qiniu AccessKey

   qiniu_secret_key: P0QRMjbbSpF4Eo_x4T8hOsnT6wne9jYmkcF7aF32  # 你的 qiniu SecretKey

   qiniu_bucket: jdstore-demo2  # 你的 qiniu bucket

   qiniu_bucket_domain: oqvf5d9pq.bkt.clouddn.com  # 你的 qiniu bucket domain

  #  AWS_ACCESS_KEY_ID: "xxxx"
  #  AWS_SECRET_ACCESS_KEY: "xxxx"
  #  AWS_REGION: "xxxx"
  #  AWS_BUCKET_NAME: "xxxx"
   SEND_CLOUD_USER_NAME: "solarmax_test_d8L5Nl"  # 你的 API_USER

   SEND_CLOUD_USER_KEY: "55Zn2AVgt9VGXSGq"  # 你的 API_KEY
